# Generated by Django 4.2.9 on 2025-04-21 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "contract_number",
                    models.CharField(max_length=50, verbose_name="Número de contrato"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de finalización")),
                (
                    "signing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de firma"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Valor del contrato",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="COP", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "special_clauses",
                    models.TextField(
                        blank=True, null=True, verbose_name="Cláusulas especiales"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número de referencia",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Departamento/Área",
                    ),
                ),
                (
                    "is_renewal",
                    models.BooleanField(
                        default=False, verbose_name="Es una renovación"
                    ),
                ),
                (
                    "requires_performance_bond",
                    models.BooleanField(
                        default=False, verbose_name="Requiere póliza de cumplimiento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CONTRACT", "Contrato"),
                            ("ANNEX", "Anexo"),
                            ("AMENDMENT", "Otrosí"),
                            ("PROPOSAL", "Propuesta"),
                            ("INVOICE", "Factura"),
                            ("REPORT", "Informe"),
                            ("LEGAL", "Documento legal"),
                            ("TECHNICAL", "Documento técnico"),
                            ("FINANCIAL", "Documento financiero"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de documento",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="contract_documents/", verbose_name="Archivo"
                    ),
                ),
                (
                    "is_signed",
                    models.BooleanField(default=False, verbose_name="Está firmado"),
                ),
                (
                    "signing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de firma"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número de referencia",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Versión"
                    ),
                ),
                (
                    "is_current_version",
                    models.BooleanField(default=True, verbose_name="Es versión actual"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="contracts.contract",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="contracts.contractdocument",
                        verbose_name="Documento origen",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_documents",
                        to="organizations.organization",
                        verbose_name="Organización",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de contrato",
                "verbose_name_plural": "Documentos de contrato",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "template",
                    models.TextField(blank=True, null=True, verbose_name="Plantilla"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True, verbose_name="Requiere aprobación"
                    ),
                ),
                (
                    "sequential_number",
                    models.BooleanField(
                        default=True, verbose_name="Numeración secuencial"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_types",
                        to="organizations.organization",
                        verbose_name="Organización",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de contrato",
                "verbose_name_plural": "Tipos de contrato",
                "ordering": ["name"],
                "unique_together": {("name", "tenant"), ("code", "tenant")},
            },
        ),
        migrations.CreateModel(
            name="ContractStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("REVIEW", "En revisión"),
                            ("PENDING_APPROVAL", "Pendiente de aprobación"),
                            ("APPROVED", "Aprobado"),
                            ("SIGNED", "Firmado"),
                            ("ACTIVE", "Activo"),
                            ("ON_HOLD", "Suspendido"),
                            ("COMPLETED", "Completado"),
                            ("TERMINATED", "Terminado"),
                            ("CANCELLED", "Cancelado"),
                            ("EXPIRED", "Expirado"),
                            ("ARCHIVED", "Archivado"),
                        ],
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de finalización"
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Comentarios"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cambiado por",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="contracts.contract",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_statuses",
                        to="organizations.organization",
                        verbose_name="Organización",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de contrato",
                "verbose_name_plural": "Estados de contrato",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ContractRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "revision_type",
                    models.CharField(
                        choices=[
                            ("CREATION", "Creación"),
                            ("UPDATE", "Actualización"),
                            ("AMENDMENT", "Otrosí"),
                            ("APPROVAL", "Aprobación"),
                            ("RENEWAL", "Renovación"),
                            ("TERMINATION", "Terminación"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de revisión",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Descripción del cambio"),
                ),
                (
                    "previous_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Datos anteriores"
                    ),
                ),
                (
                    "new_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Datos nuevos"
                    ),
                ),
                (
                    "revision_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de revisión"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="contracts.contract",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="contracts.contractdocument",
                        verbose_name="Documento asociado",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_revisions",
                        to="organizations.organization",
                        verbose_name="Organización",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisión de contrato",
                "verbose_name_plural": "Revisiones de contrato",
                "ordering": ["-revision_date"],
            },
        ),
        migrations.CreateModel(
            name="ContractParty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("CONTRACTOR", "Contratista"),
                            ("CONTRACTING", "Contratante"),
                            ("BENEFICIARY", "Beneficiario"),
                            ("SUPERVISOR", "Supervisor"),
                            ("GUARANTOR", "Garante"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de parte",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "identification_type",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de identificación",
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número de identificación",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Rol en el contrato",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="contracts.contract",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_participations",
                        to="organizations.organization",
                        verbose_name="Organización",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_parties",
                        to="organizations.organization",
                        verbose_name="Organización",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parte de contrato",
                "verbose_name_plural": "Partes de contrato",
                "ordering": ["party_type", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="contracts.contracttype",
                verbose_name="Tipo de contrato",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="parent_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewals",
                to="contracts.contract",
                verbose_name="Contrato origen",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_contracts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Supervisor",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="organizations.organization",
                verbose_name="Organización",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contract",
            unique_together={("contract_number", "tenant")},
        ),
    ]
