# Generated by Django 4.2.9 on 2025-04-22 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_initial"),
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "invoice_number",
                    models.CharField(max_length=50, verbose_name="Número de cuenta"),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Título/Concepto"),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("ORGANIZATION", "Organización"),
                            ("USER", "Usuario"),
                            ("EXTERNAL", "Externo"),
                        ],
                        default="ORGANIZATION",
                        max_length=20,
                        verbose_name="Tipo de receptor",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nombre del receptor externo",
                    ),
                ),
                (
                    "recipient_identification",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Identificación del receptor",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Fecha de emisión")),
                ("due_date", models.DateField(verbose_name="Fecha de vencimiento")),
                (
                    "period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha inicio del periodo"
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha fin del periodo"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Subtotal"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Descuentos",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Total"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="COP", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "payment_terms",
                    models.TextField(
                        blank=True, null=True, verbose_name="Términos de pago"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Referencia"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Método de pago",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Está pagada"),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de pago"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoice_documents/",
                        verbose_name="Documento",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="contracts.contract",
                        verbose_name="Contrato asociado",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Emisor",
                    ),
                ),
                (
                    "recipient_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_invoices",
                        to="organizations.organization",
                        verbose_name="Organización receptora",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario receptor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="organizations.organization",
                        verbose_name="Organización",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta de cobro",
                "verbose_name_plural": "Cuentas de cobro",
                "ordering": ["-issue_date", "-created_at"],
                "unique_together": {("invoice_number", "tenant")},
            },
        ),
        migrations.CreateModel(
            name="InvoiceStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("SUBMITTED", "Enviada"),
                            ("REVIEW", "En revisión"),
                            ("PENDING_APPROVAL", "Pendiente de aprobación"),
                            ("APPROVED", "Aprobada"),
                            ("REJECTED", "Rechazada"),
                            ("PAID", "Pagada"),
                            ("CANCELLED", "Cancelada"),
                            ("ARCHIVED", "Archivada"),
                        ],
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de finalización"
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Comentarios"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cambiado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="invoices.invoice",
                        verbose_name="Cuenta de cobro",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_statuses",
                        to="organizations.organization",
                        verbose_name="Organización",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de cuenta de cobro",
                "verbose_name_plural": "Estados de cuenta de cobro",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Semanal"),
                            ("BIWEEKLY", "Quincenal"),
                            ("MONTHLY", "Mensual"),
                            ("BIMONTHLY", "Bimestral"),
                            ("QUARTERLY", "Trimestral"),
                            ("SEMIANNUAL", "Semestral"),
                            ("ANNUAL", "Anual"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de programación",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de finalización"
                    ),
                ),
                (
                    "custom_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Días personalizados"
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Para cuentas mensuales o trimestrales",
                        null=True,
                        verbose_name="Día del mes",
                    ),
                ),
                (
                    "is_auto_generate",
                    models.BooleanField(
                        default=True, verbose_name="Generar automáticamente"
                    ),
                ),
                (
                    "auto_approve",
                    models.BooleanField(
                        default=False, verbose_name="Aprobar automáticamente"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "last_generated",
                    models.DateField(
                        blank=True, null=True, verbose_name="Última generación"
                    ),
                ),
                (
                    "next_generation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima generación"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Valor"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_schedules",
                        to="contracts.contract",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_schedules",
                        to="organizations.organization",
                        verbose_name="Organización",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Programación de cuenta de cobro",
                "verbose_name_plural": "Programaciones de cuenta de cobro",
                "ordering": ["-is_active", "contract", "schedule_type"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=15,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Precio unitario"
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentaje de impuesto",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Monto de impuesto",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentaje de descuento",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Monto de descuento",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Subtotal"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Total"
                    ),
                ),
                (
                    "contract_item",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ítem de contrato",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.invoice",
                        verbose_name="Cuenta de cobro",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                        verbose_name="Organización",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de cuenta de cobro",
                "verbose_name_plural": "Ítems de cuenta de cobro",
                "ordering": ["invoice", "order"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("REVIEW", "Revisión"),
                            ("FIRST_APPROVAL", "Primera aprobación"),
                            ("SECOND_APPROVAL", "Segunda aprobación"),
                            ("FINANCIAL_APPROVAL", "Aprobación financiera"),
                            ("FINAL_APPROVAL", "Aprobación final"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de aprobación",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de asignación"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha límite"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobada"),
                            ("REJECTED", "Rechazada"),
                            ("RETURNED", "Devuelta para correcciones"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Resultado",
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de aprobación/rechazo",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Comentarios"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobador",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="invoices.invoice",
                        verbose_name="Cuenta de cobro",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_approvals",
                        to="organizations.organization",
                        verbose_name="Organización",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aprobación de cuenta de cobro",
                "verbose_name_plural": "Aprobaciones de cuenta de cobro",
                "ordering": ["invoice", "approval_type", "-assigned_date"],
                "unique_together": {("invoice", "approval_type", "approver")},
            },
        ),
    ]
