# Generated by Django 4.2.9 on 2025-04-20 23:11

from django.db import migrations, models
import django_tenants.postgresql_backend.base
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True,
                        help_text="¿Es este el dominio principal de la organización?",
                        verbose_name="Dominio principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dominio",
                "verbose_name_plural": "Dominios",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "subdomain",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Subdominio"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="organization_logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email de contacto",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ciudad"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Colombia", max_length=100, verbose_name="País"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Código postal",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="NIT"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#1976D2", max_length=20, verbose_name="Color primario"
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#424242",
                        max_length=20,
                        verbose_name="Color secundario",
                    ),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Máximo de usuarios"
                    ),
                ),
                (
                    "max_storage_gb",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Almacenamiento máximo (GB)"
                    ),
                ),
                (
                    "paid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Pagado hasta"
                    ),
                ),
                (
                    "on_trial",
                    models.BooleanField(
                        default=True, verbose_name="En período de prueba"
                    ),
                ),
                (
                    "trial_ends",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin del período de prueba"
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("GOV_ENTITY", "Entidad Gubernamental"),
                            ("CONTRACTOR", "Contratista"),
                            ("PROVIDER", "Proveedor"),
                            ("OTHER", "Otro"),
                        ],
                        default="GOV_ENTITY",
                        max_length=20,
                        verbose_name="Tipo de organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organización",
                "verbose_name_plural": "Organizaciones",
            },
        ),
        migrations.CreateModel(
            name="OrganizationInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Email del invitado"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Token de invitación"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("MANAGER", "Gestor"),
                            ("SUPERVISOR", "Supervisor"),
                            ("CONTRACTOR", "Contratista"),
                            ("APPROVER", "Aprobador"),
                            ("VIEWER", "Visualizador"),
                        ],
                        max_length=20,
                        verbose_name="Rol a asignar",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("ACCEPTED", "Aceptada"),
                            ("REJECTED", "Rechazada"),
                            ("EXPIRED", "Expirada"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expira en")),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aceptada en"
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitación a organización",
                "verbose_name_plural": "Invitaciones a organizaciones",
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("MANAGER", "Gestor"),
                            ("SUPERVISOR", "Supervisor"),
                            ("CONTRACTOR", "Contratista"),
                            ("APPROVER", "Aprobador"),
                            ("VIEWER", "Visualizador"),
                        ],
                        max_length=20,
                        verbose_name="Rol en la organización",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Cargo"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Departamento/Área",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de finalización"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
            ],
            options={
                "verbose_name": "Miembro de organización",
                "verbose_name_plural": "Miembros de organizaciones",
            },
        ),
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "require_double_approval",
                    models.BooleanField(
                        default=False, verbose_name="Requerir doble aprobación"
                    ),
                ),
                (
                    "allow_self_approval",
                    models.BooleanField(
                        default=False, verbose_name="Permitir auto-aprobación"
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notificaciones por email"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Notificaciones por SMS"
                    ),
                ),
                (
                    "force_password_change",
                    models.BooleanField(
                        default=True, verbose_name="Forzar cambio de contraseña"
                    ),
                ),
                (
                    "password_expiry_days",
                    models.IntegerField(
                        default=90, verbose_name="Días para expiración de contraseña"
                    ),
                ),
                (
                    "session_timeout_minutes",
                    models.IntegerField(
                        default=30,
                        verbose_name="Tiempo de inactividad para cierre de sesión (minutos)",
                    ),
                ),
                (
                    "fiscal_year_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inicio de año fiscal"
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        default="COP",
                        max_length=3,
                        verbose_name="Moneda predeterminada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de organización",
                "verbose_name_plural": "Configuraciones de organizaciones",
            },
        ),
    ]
